// components/Table.js
import React from 'react';

const IncomStatement = () => {
    const data = [
        { name: 'John Doe', rollNumber: '001' },
        { name: 'Jane Smith', rollNumber: '002' },
        // Add more data as needed
    ];
    return (
        <div class="table-responsive table-new">
        <table class="table">
        <thead>
        <tr>
        <th>Breakdown</th>
        <th>2022-12-31</th>
        <th>2021-12-31</th>
        <th>2020-12-31</th>
        <th>2019-12-31</th>
        <th>2018-12-31</th>
        </tr>
        </thead>
        <tbody>
        <tr>
        <td>Type</td>
        <td>
        yearly
        </td>
        <td>
        yearly
        </td>
        <td>
        yearly
        </td>
        <td>
        yearly
        </td>
        <td>
        yearly
        </td>
        </tr>
        <tr>
        <td>Date</td>
        <td>
        2022-12-31
        </td>
        <td>
        2021-12-31
        </td>
        <td>
        2020-12-31
        </td>
        <td>
        2019-12-31
        </td>
        <td>
        2018-12-31
        </td>
        </tr>
        <tr>
        <td>Income before tax</td>
        <td>
        71328.00M
        </td>
        <td>
        90734.00M
        </td>
        <td>
        48082.00M
        </td>
        <td>
        39625.00M
        </td>
        <td>
        34913.00M
        </td>
        </tr>
        <tr>
        <td>Minority interest</td>
        <td>
        -
        </td>
        <td>
        -
        </td>
        <td>
        -
        </td>
        <td>
        -
        </td>
        <td>
        -
        </td>
        </tr>
        <tr>
        <td>Net income</td>
        <td>
        59972.00M
        </td>
        <td>
        76033.00M
        </td>
        <td>
        40269.00M
        </td>
        <td>
        34343.00M
        </td>
        <td>
        30736.00M
        </td>
        </tr>
        <tr>
        <td>Selling general administrative</td>
        <td>
        15724.00M
        </td>
        <td>
        13510.00M
        </td>
        <td>
        11052.00M
        </td>
        <td>
        9551.00M
        </td>
        <td>
        8126.00M
        </td>
        </tr>
        <tr>
        <td>Selling and marketing expenses</td>
        <td>
        26567.00M
        </td>
        <td>
        22912.00M
        </td>
        <td>
        17946.00M
        </td>
        <td>
        18464.00M
        </td>
        <td>
        16333.00M
        </td>
        </tr>
        <tr>
        <td>Gross profit</td>
        <td>
        156633.00M
        </td>
        <td>
        146698.00M
        </td>
        <td>
        97795.00M
        </td>
        <td>
        89961.00M
        </td>
        <td>
        77270.00M
        </td>
        </tr>
        <tr>
        <td>Reconciled depreciation</td>
        <td>
        15928.00M
        </td>
        <td>
        12441.00M
        </td>
        <td>
        13697.00M
        </td>
        <td>
        11781.00M
        </td>
        <td>
        9035.00M
        </td>
        </tr>
        <tr>
        <td>Ebit</td>
        <td>
        74842.00M
        </td>
        <td>
        78714.00M
        </td>
        <td>
        41224.00M
        </td>
        <td>
        34231.00M
        </td>
        <td>
        36463.00M
        </td>
        </tr>
        <tr>
        <td>Ebitda</td>
        <td>
        90770.00M
        </td>
        <td>
        91155.00M
        </td>
        <td>
        54921.00M
        </td>
        <td>
        49406.00M
        </td>
        <td>
        45498.00M
        </td>
        </tr>
        <tr>
        <td>Depreciation and amortization</td>
        <td>
        15928.00M
        </td>
        <td>
        12441.00M
        </td>
        <td>
        13697.00M
        </td>
        <td>
        15175.00M
        </td>
        <td>
        9035.00M
        </td>
        </tr>
        <tr>
        <td>Non operating income net other</td>
        <td>
        -3514.00000M
        </td>
        <td>
        12020.00M
        </td>
        <td>
        6858.00M
        </td>
        <td>
        5394.00M
        </td>
        <td>
        8592.00M
        </td>
        </tr>
        <tr>
        <td>Operating income</td>
        <td>
        74842.00M
        </td>
        <td>
        78714.00M
        </td>
        <td>
        41224.00M
        </td>
        <td>
        34231.00M
        </td>
        <td>
        26321.00M
        </td>
        </tr>
        <tr>
        <td>Other operating expenses</td>
        <td>
        207994.00M
        </td>
        <td>
        178923.00M
        </td>
        <td>
        141303.00M
        </td>
        <td>
        125929.00M
        </td>
        <td>
        105427.00M
        </td>
        </tr>
        <tr>
        <td>Interest expense</td>
        <td>
        357.00M
        </td>
        <td>
        346.00M
        </td>
        <td>
        135.00M
        </td>
        <td>
        100.00M
        </td>
        <td>
        114.00M
        </td>
        </tr>
        <tr>
        <td>Tax provision</td>
        <td>
        11356.00M
        </td>
        <td>
        14701.00M
        </td>
        <td>
        7813.00M
        </td>
        <td>
        5282.00M
        </td>
        <td>
        4177.00M
        </td>
        </tr>
        <tr>
        <td>Interest income</td>
        <td>
        2174.00M
        </td>
        <td>
        1499.00M
        </td>
        <td>
        1865.00M
        </td>
        <td>
        2427.00M
        </td>
        <td>
        1878.00M
        </td>
        </tr>
        <tr>
        <td>Net interest income</td>
        <td>
        1817.00M
        </td>
        <td>
        1153.00M
        </td>
        <td>
        1730.00M
        </td>
        <td>
        2327.00M
        </td>
        <td>
        1764.00M
        </td>
        </tr>
        <tr>
        <td>Extraordinary items</td>
        <td>
        -
        </td>
        <td>
        -
        </td>
        <td>
        -
        </td>
        <td>
        -
        </td>
        <td>
        -
        </td>
        </tr>
        <tr>
        <td>Non recurring</td>
        <td>
        -
        </td>
        <td>
        -
        </td>
        <td>
        -
        </td>
        <td>
        -
        </td>
        <td>
        -
        </td>
        </tr>
        <tr>
        <td>Other items</td>
        <td>
        -
        </td>
        <td>
        -
        </td>
        <td>
        -
        </td>
        <td>
        -
        </td>
        <td>
        -
        </td>
        </tr>
        <tr>
        <td>Income tax expense</td>
        <td>
        11356.00M
        </td>
        <td>
        14701.00M
        </td>
        <td>
        7813.00M
        </td>
        <td>
        5282.00M
        </td>
        <td>
        4177.00M
        </td>
        </tr>
        <tr>
        <td>Total revenue</td>
        <td>
        282836.00M
        </td>
        <td>
        257637.00M
        </td>
        <td>
        182527.00M
        </td>
        <td>
        161857.00M
        </td>
        <td>
        136819.00M
        </td>
        </tr>
        <tr>
        <td>Total operating expenses</td>
        <td>
        81791.00M
        </td>
        <td>
        67984.00M
        </td>
        <td>
        56571.00M
        </td>
        <td>
        54033.00M
        </td>
        <td>
        45878.00M
        </td>
        </tr>
        <tr>
        <td>Cost of revenue</td>
        <td>
        126203.00M
        </td>
        <td>
        110939.00M
        </td>
        <td>
        84732.00M
        </td>
        <td>
        71896.00M
        </td>
        <td>
        59549.00M
        </td>
        </tr>
        <tr>
        <td>Total other income expense net</td>
        <td>
        -3514.00000M
        </td>
        <td>
        12020.00M
        </td>
        <td>
        6858.00M
        </td>
        <td>
        5394.00M
        </td>
        <td>
        3521.00M
        </td>
        </tr>
        <tr>
        <td>Discontinued operations</td>
        <td>
        -
        </td>
        <td>
        -
        </td>
        <td>
        -
        </td>
        <td>
        -
        </td>
        <td>
        -
        </td>
        </tr>
        <tr>
        <td>Net income from continuing ops</td>
        <td>
        59972.00M
        </td>
        <td>
        76033.00M
        </td>
        <td>
        40269.00M
        </td>
        <td>
        34343.00M
        </td>
        <td>
        30736.00M
        </td>
        </tr>
        <tr>
        <td>Net income applicable to common shares</td>
        <td>
        59972.00M
        </td>
        <td>
        76033.00M
        </td>
        <td>
        40269.00M
        </td>
        <td>
        34343.00M
        </td>
        <td>
        30736.00M
        </td>
        </tr>
        <tr>
        <td>Preferred stock and other adjustments</td>
        <td>
        -
        </td>
        <td>
        -
        </td>
        <td>
        -
        </td>
        <td>
        -
        </td>
        <td>
        -
        </td>
        </tr>
        </tbody>
        </table>
        </div>
    );
};

export default IncomStatement;
