import { Inter } from 'next/font/google'
import './globals.css'
import Footer from './components/footer'
import Navigation from './navigation/page'
import Home from './page'
import Disclaimer from './disclaimer/page'
import Profile from './profile/page'
const inter = Inter({ subsets: ['latin'] })
import Cards from './components/cards'
import Premium from './components/premium'
import portal from './portal/page'


export const metadata = {
  title: 'Kalkine',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <title>Research Content &amp; Publishing Services | Haanuwise</title>
      <meta name="robots" content="noindex, follow" />
      <meta name="description" content/>
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
      <link rel="shortcut icon" type="image/x-icon" href="https://b2b.kalkine.co.in/assets/web/images/favicon.ico"/>
      <link rel="stylesheet" href="https://b2b.kalkine.co.in/assets/web/css/vendor/bootstrap.min.css?v=3"/>
      <link rel="stylesheet" href="https://b2b.kalkine.co.in/assets/web/css/plugins/slick.css?v=3"/>
      <link rel="stylesheet" href="https://b2b.kalkine.co.in/assets/web/css/plugins/font-awesome.css?v=3"/>
      <link rel="stylesheet" href="https://b2b.kalkine.co.in/assets/web/css/plugins/icomoon.css?v=3"/>
      <link rel="stylesheet" href="https://b2b.kalkine.co.in/assets/web/css/plugins/plugins.css?v=3"/>
      <link rel="stylesheet" href="https://b2b.kalkine.co.in/assets/web/css/style.css?ver=234"/>
      </head>
      <body >
      {/* <Navigation/>  
       <Premium/> */}
      {children}
       {/* <Footer Title={'Our Design'}/> 
       <Disclaimer/> 
      */}
    </body>
    </html>
  )
}
